spring:
    profiles:
        active: pro
    data:
        mongodb:
            hosts:
              - 192.168.99.100
            port: 32768
            database: test
            connectionsPerHost: 4
            readPreference: primaryPreferred
    jackson:
        serialization.indent_output: false